package sbnz.rules;
import ftn.sbnz.model.company.Company;
import ftn.sbnz.model.job_offer.JobOffer;
import ftn.sbnz.model.user.JobSeekerRanking;
import ftn.sbnz.model.enums.MedalRank;
import java.time.LocalDate;
import java.sql.Timestamp;

rule "Job Offer Status - GOLD - row (0)"
agenda-group "job-offer-status"
    when
        jobOffer: JobOffer(companyId: company.getId(), offerId: id,
                            datePosted.after(Timestamp.valueOf(LocalDate.now().minusDays(21).atStartOfDay())),
                            medal == MedalRank.SILVER)
        and
        company: Company(id == companyId, medal.getValue() >= MedalRank.GOLD.getValue())
        and
        Number(intValue >= 3) from accumulate (JobSeekerRanking(jobOffer.getId() == offerId), count(1))
    then
        modify(jobOffer) {
            setMedal(MedalRank.GOLD)
        }
        System.out.println("Job Offer for position " + jobOffer.getPosition().getTitle() + " status set to GOLD");
end

rule "Job Offer Status - BRONZE - row (1)"
agenda-group "job-offer-status"
    when
        jobOffer: JobOffer(companyId: company.getId(), offerId: id,
                            datePosted.after(Timestamp.valueOf(LocalDate.now().minusDays(7).atStartOfDay())),
                            medal == MedalRank.NONE)
        and
        company: Company(id == companyId, medal.getValue() >= MedalRank.NONE.getValue())
        and
        Number(intValue >= 1) from accumulate (JobSeekerRanking(jobOffer.getId() == offerId), count(1))
    then
        modify(jobOffer) {
            setMedal(MedalRank.BRONZE)
        }
        System.out.println("Job Offer for position " + jobOffer.getPosition().getTitle() + " status set to BRONZE");
end

rule "Job Offer Status - SILVER - row (2)"
agenda-group "job-offer-status"
    when
        jobOffer: JobOffer(companyId: company.getId(), offerId: id,
                            datePosted.after(Timestamp.valueOf(LocalDate.now().minusDays(14).atStartOfDay())),
                            medal == MedalRank.BRONZE)
        and
        company: Company(id == companyId, medal.getValue() >= MedalRank.NONE.getValue())
        and
        Number(intValue >= 1) from accumulate (JobSeekerRanking(jobOffer.getId() == offerId), count(1))
    then
        modify(jobOffer) {
            setMedal(MedalRank.SILVER)
        }
        System.out.println("Job Offer for position " + jobOffer.getPosition().getTitle() + " status set to SILVER");
end


